apiVersion: v1
appVersion: "3.2.1"
description: "Async Scala-Akka-Netty based Load Test Tool "
engine: gotpl
home: https://github.com/giantswarm/gatling-app
icon: https://gatling.io/wp-content/uploads/2019/04/logo-gatling-transparent@15x.svg
name: gatling-app
sources:
- https://raw.githubusercontent.com/giantswarm/gatling-app/v[[ .Version ]]/README.md
- https://github.com/gatling/gatling
version: [[ .Version ]]
